### ISSUE TITLE
Cost -1 doesn't go well with a recent Unciv change

### ISSUE THREAD

**Issue by SomeTroglodyte** [RealBamboolord/LOTR-reworked#19]
See https://github.com/yairm210/Unciv/pull/9621

Likely a very old decision to get around some outdated limitation - not touching cost and adding the Unbuildable unique to all those Rings etc would likely be the proper solution?

**Comment by SeventhM** [comment]
The other alternative is to switch the cost from -1 to 0 as it was likely intended. Having things work on 0 instead of -1 is the more proper of a solution as -1 leads to weird looking negative production costs on longer game speeds

**Comment by RealBamboolord** [comment]
Will fix

**Comment by SomeTroglodyte** [comment]
:shrug:  just a heads up that someone :angel: fiddled with something that might affect you :+1:

> switch the cost from -1 to 0 as it was likely intended

I was unclear: by 'not touching cost' I meant remove the mod's cost lines. Explicitly stating 0 now has a new intended usecase - see that PR. Might be your boat or not.

> -1 leads to weird looking
I read your PR as aiming to fix that? Wait - did you fix the "running vanilla now has actually 0 cost for buildings that should default to the tech era's costs" thing yet?

> Will fix
Be aware that for testing you'd better use a point where that PR is already merged... Not yet a release.

**Comment by SeventhM** [comment]
> Wait - did you fix the "running vanilla now has actually 0 cost for buildings that should default to the tech era's costs" thing yet?

Just noticed that message in the PR. Fixed
