### ISSUE TITLE
Not really an issue but more of a question

### ISSUE THREAD

**Issue by DELUXEHUNTER** [RealBamboolord/LOTR-reworked#25]
This isn't really an issue, but more of a question, why not remove association with ravignir's original LOTR mod, they haven't really worked on the mod for a long while, or 2-3 years.

 Well I have multiple questions, what are the plans for this mod, and why are the victory types all still the base-game one with the exception of the ring victory and domination? 

Sorry if this is too much or a misuse of the issue page, or if I seem rude, I'm just curious.

If you comment I will not answer till morning its 6am

**Comment by RealBamboolord** [comment]
> This isn't really an issue, but more of a question, why not remove association with ravignir's original LOTR mod, they haven't really worked on the mod for a long while, or 2-3 years.
>
Well actually, he is working on the project again, we are collaborating for version 2.0
> Well I have multiple questions, what are the plans for this mod, and why are the victory types all still the base-game one with the exception of the ring victory and domination?
>
Currently we have only Ring and Domination victory, and there are no plans of adding more, we only plan on reworking Ring victory
> Sorry if this is too much or a misuse of the issue page, or if I seem rude, I'm just curious.
>
Not at all, you are welcome
> If you comment I will not answer till morning its 6am
>
That's alright, I don't expect anything to be fast, I'm more of a Slowpoke myself
