### ISSUE TITLE
Some units are not visible.

### ISSUE THREAD

**Issue by havevgen13** [RealBamboolord/LOTR-reworked#29]
Hi, I'm a Lord of the Rings fan.  I have a skin problem.  Some units are not visible.  Is this a bug or should it be?

**Comment by RealBamboolord** [comment]
Not a bug, not every unit has a skin.
It is definately not the state the mod should be in, but currently there are other priorities

**Comment by havevgen13** [comment]
If not a secret.  What are you planning and when to expect an update?

**Comment by RealBamboolord** [comment]
It will still take a while, but me and Ravignir are working on a big overhaul
